### ISSUE TITLE
Una nota di colore

### ISSUE THREAD

**Issue by matteobaccan** [robfrank/exercises#78]
Non so a cosa ti sei ispirato, ma quando ero piccolo guardavo questa trasmissione in TV

Buzz Fizz Quiz

https://www.rsi.ch/archivi/rivediamoli/buzz-fizz-quiz/

Col Sig Piantoni, la Maristella e il Bigio ... e il tuo repo mi ha fatto tornare bambino, anche solo per qualche secondo

**Comment by robfrank** [comment]
e' uno dei coding kata piu' famosi ed usati nei colloqui

https://www.codurance.com/katas/fizzbuzz

io l'ho usato per fare esperimenti. ho messo una CLI, creo una native image. cose simili

**Comment by matteobaccan** [comment]
confido non scriverò mai codice ai colloqui, senza il mio pc e i trilioni di automatismi ho l'agilità di una gibbone in una giornata di agosto
